### PR TITLE
Fixing readFile method name.

### PR DESCRIPTION
**Pull request by ekynoxe**
I found this today while trying to use the module.

### CODE REVIEW

**Comment by hnq90** [comment]
@ekynoxe Thanks for the PR but I think you should change current `readFile` to `readFromFile` then change `readToFile` to `readFile`.
Would you like to help me change it?

**Comment by nowtech** [comment]
I have made a similar change in my local project - will you do merge overnight?

**Comment by ekynoxe** [comment]
Hi @hnq90 . I didn't change anything else because I wasn't sure about the other implementations. I believe doing what you propose, we'll also have to change the adaptors for android and iOS, which I don't think is the right thing to do, given that you'd want your library to be a drop in replacement for the original.
Or am I missing something?

**Comment by ekynoxe** [comment]
@hnq90 I think I know what you mean. Right now, with my change, there is also a task called `readFile`, and you want to disambiguate so would like to rename the task to `readFromFile`. Is that correct?

**Comment by hnq90** [comment]
@ekynoxe Yes, correct. `readFile` was existed so we should to change it before rename `readToFile ` to `readFile`.

**Comment by nowtech** [comment]
Thats how i fixed - will submit a pull request if you want?

**Comment by ekynoxe** [comment]
Ok @hnq90. @nowtech I'll do this today.

**Comment by ekynoxe** [comment]
Hi guys, I've updated the code. Can you let me know if that's what you meant @hnq90 ?

**Comment by hnq90** [comment]
@ekynoxe  I merged your PR. Thank you.

**Pull request merged**
